replicaCount: 1

image:
  repository: ghcr.io/rodmhgl/k8s-test-app
  tag: "latest"

environment: "development"

database:
  enabled: true
  connectionString: "postgres://user:password@postgres-service:5432/testdb"

persistentVolume:
  enabled: true
  # size: 1Gi
  # mountPath: /data
