replicaCount: 1

image:
  repository: ghcr.io/rodmhgl/k8s-test-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 31080

environment: "development"

database:
  enabled: true
  connectionString: "postgres://user:password@postgres-service:5432/testdb"

persistentVolume:
  enabled: true
  size: 1Gi
  mountPath: /data
