apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}k8s-test-app-config
  labels:
    app: k8s-test-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  COLOR_THEME: {{ .Values.colorTheme | default "blue" | quote }}
  PORT: "3000"