apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}k8s-test-app
  labels:
    app: k8s-test-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1}}
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
      - name: k8s-test-app
        image: "{{ .Values.image.repository | default "ghcr.io/rodmhgl/k8s-test-app" }}:{{ .Values.image.tag | default "latest"}}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.service.targetPort | default 3000 }}
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.namePrefix }}k8s-test-app-config
              key: ENVIRONMENT
        - name: COLOR_THEME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.namePrefix }}k8s-test-app-config
              key: COLOR_THEME
        {{- if .Values.database.enabled }}
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{ .Values.namePrefix }}k8s-test-app-db-secret
              key: DB_CONNECTION_STRING
        {{- end }}
        {{- if .Values.persistentVolume.enabled }}
        - name: PVC_PATH
          value: {{ .Values.persistentVolume.mountPath | default "/data" | quote }}
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: test-data
          mountPath: {{ .Values.persistentVolume.mountPath | default "/data" | quote }}
        {{- end }}
      {{- if .Values.persistentVolume.enabled }}
      volumes:
      - name: test-data
        persistentVolumeClaim:
          claimName: {{ .Values.namePrefix }}k8s-test-app-pvc
      {{- end }}