{{- if .Values.database.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namePrefix }}k8s-test-app-db-secret
  labels:
    app: k8s-test-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DB_CONNECTION_STRING: {{ .Values.database.connectionString | b64enc }}
{{- end }}