apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}k8s-test-app-service
  labels:
    app: k8s-test-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: k8s-test-app
  ports:
  - port: {{ .Values.service.port | default 80 }}
    targetPort: {{ .Values.service.targetPort | default 3000 }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort | default 30080 }}
    {{- end }}