apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app
  labels:
    app: k8s-test-app
    release: k8s-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
        - name: k8s-test-app
          image: ghcr.io/rodmhgl/k8s-test-app:latest
          imagepullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: k8s-test-app-config
                  key: ENVIRONMENT
            - name: COLOR_THEME
              valueFrom:
                configMapKeyRef:
                  name: k8s-test-app-config
                  key: COLOR_THEME
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: k8s-test-app-db-secret
                  key: DB_CONNECTION_STRING
            - name: PVC_PATH
              value: "/data"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: test-data
              mountPath: /data
      volumes:
        - name: test-data
          persistentVolumeClaim:
            claimName: k8s-test-app-pvc
