apiVersion: v1
kind: Secret
metadata:
  name: k8s-test-app-db-secret
type: Opaque
data:
  # Example: echo -n "postgres://user:password@postgres-service:5432/testdb" | base64
  # This isn't an actual database connection string
  DB_CONNECTION_STRING: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi90ZXN0ZGI=