name: Deploy K8s Test App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: k8s-test-app
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
    
    # - name: Set up Kubernetes tools
    #   uses: azure/setup-kubectl@v3
      
    # - name: Set up Kustomize
    #   run: |
    #     curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    #     mv kustomize /usr/local/bin/
    
    # - name: Configure Kubernetes credentials
    #   uses: azure/k8s-set-context@v3
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    # - name: Determine environment
    #   id: env
    #   run: |
    #     if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
    #       echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> "$GITHUB_ENV"
    #     else
    #       echo "ENVIRONMENT=development" >> "$GITHUB_ENV"
    #     fi
    
    # - name: Update Kustomize image
    #   run: |
    #     cd overlays/${{ env.ENVIRONMENT }}
    #     kustomize edit set image k8s-test-app=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl create namespace k8s-test-app --dry-run=client -o yaml | kubectl apply -f -
    #     kustomize build overlays/${{ env.ENVIRONMENT }} | kubectl apply -f -
    #     kubectl rollout status deployment/${{ env.ENVIRONMENT }}-k8s-test-app -n k8s-test-app --timeout=180s
    
    # - name: Get service URL
    #   run: |
    #     echo "Application deployed. Service URL:"
    #     kubectl get service ${{ env.ENVIRONMENT }}-k8s-test-app-service -n k8s-test-app -o jsonpath="{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}"